server = 'quarto-vm2.southeastasia.cloudapp.azure.com'
port = '14336'
database = 'LONE_PTWP'
username = 'quartobi'
password = 'Rohs85#'

url_PriceCompute = 'https://prod-37.southeastasia.logic.azure.com:443/workflows/8d3ee9a9b3bc46868eca0b23032e7c13/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=9TAwgb1TlIaN5SBi40BSN6S87LDXZSxY5Iniz1N-ND8'
url_PaymentPosting = 'https://prod-44.southeastasia.logic.azure.com:443/workflows/389a4f7fe50a4859b5ad82e0c1e07a06/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=df4frEQoTAazd3SFMO6bs0NYlOW1GXFHXk5CnnUccko'
url_RevertPayment = 'https://prod-49.southeastasia.logic.azure.com:443/workflows/cd58a1c846e54a2794b8fac4c60f1b44/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=4om0C7ETdfPwQa6i4xbz-Wc2NBGzsRSJokqwlSiwH_U'