server = 'lintramax-vm1cc.southeastasia.cloudapp.azure.com'
port = '14557'
database = 'LONE_PTWP'
username = 'quartobi'
password = 'Rohs85#'

url_PriceCompute = 'https://prod-42.southeastasia.logic.azure.com:443/workflows/0f38ba5ca84b424985f8413abb07d91a/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Qt3eD_7bM5FWJc6NNKlBDLmwUSL_ZQAXASNrB24z1tY'
url_PaymentPosting = 'https://prod-16.southeastasia.logic.azure.com:443/workflows/2deef8b431bd4369a73b39cf2709945c/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Oc7hwAgIgXQ1Q9Sv4Frvry6C_lh3px-MDdyid4wJaxw'
url_RevertPayment = 'https://prod-58.southeastasia.logic.azure.com:443/workflows/dfdc9842a4084277be4adcb902c0360d/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=gNBgGMYbFkVIwto-He418NIvlRrRwWX9e27hIa0tArs'